// Photos for the Plant Database page (plant-database.html).
//
// plant-data.js is regenerated every night from the Google Sheet, so the photos are listed here instead.
// A photo set is matched to a plant by BOTANICAL NAME (the first name shown on the card). `names` lists every
// spelling that should match: the first is the correct spelling, any others are how the Sheet currently writes it,
// so the photo keeps matching after the Sheet is corrected.
// Each file name below exists in three sizes: plant-photos/thumb/<file>.webp (200x200 card thumbnail),
// plant-photos/medium/<file>.webp (800px) and plant-photos/large/<file>.webp (1200px, used in the pop-up).
//
// To add a photo: convert it to those three sizes (sRGB, metadata stripped), add a line here, commit all four files.
window.PLANT_PHOTOS = [
  { names: ["Achillea millefolium"], files: ["achillea-millefolium"] },
  { names: ["Ageratina altissima"], files: ["ageratina-altissima"] },
  { names: ["Anaphalis margaritacea"], files: ["anaphalis-margaritacea"] },
  { names: ["Aquilegia canadensis"], files: ["aquilegia-canadensis"] },
  { names: ["Asclepias exaltata"], files: ["asclepias-exaltata"] },
  { names: ["Asclepias incarnata"], files: ["asclepias-incarnata"] },
  { names: ["Asclepias syriaca"], files: ["asclepias-syriaca"] },
  { names: ["Asclepias tuberosa"], files: ["asclepias-tuberosa"] },
  { names: ["Campanulastrum americanum"], files: ["campanulastrum-americanum"] },
  { names: ["Campsis radicans"], files: ["campsis-radicans"] },
  { names: ["Chamaecrista fasciculata"], files: ["chamaecrista-fasciculata"] },
  { names: ["Chasmanthium latifolium"], files: ["chasmanthium-latifolium"] },
  { names: ["Claytonia virginica"], files: ["claytonia-virginica"] },
  { names: ["Clinopodium vulgare"], files: ["clinopodium-vulgare"] },
  { names: ["Conoclinium coelestinum"], files: ["conoclinium-coelestinum-1","conoclinium-coelestinum-2"] },
  { names: ["Coreopsis lanceolata"], files: ["coreopsis-lanceolata"] },
  { names: ["Cystopteris protrusa"], files: ["cystopteris-protrusa"] },
  { names: ["Danthonia spicata"], files: ["danthonia-spicata"] },
  { names: ["Delphinium tricorne"], files: ["delphinium-tricorne"] },
  { names: ["Dicentra cucullaria"], files: ["dicentra-cucullaria"] },
  { names: ["Echinacea purpurea"], files: ["echinacea-purpurea"] },
  { names: ["Erigeron pulchellus"], files: ["erigeron-pulchellus"] },
  { names: ["Eryngium yuccifolium"], files: ["eryngium-yuccifolium"] },
  { names: ["Erythronium albidum"], files: ["erythronium-albidum"] },
  { names: ["Erythronium americanum"], files: ["erythronium-americanum"] },
  { names: ["Eupatorium perfoliatum"], files: ["eupatorium-perfoliatum"] },
  { names: ["Euphorbia corollata"], files: ["euphorbia-corollata"] },
  { names: ["Filipendula rubra"], files: ["filipendula-rubra"] },
  { names: ["Gentiana andrewsii"], files: ["gentiana-andrewsii"] },
  { names: ["Geranium maculatum"], files: ["geranium-maculatum"] },
  { names: ["Helianthus divaricatus"], files: ["helianthus-divaricatus"] },
  { names: ["Helianthus occidentalis"], files: ["helianthus-occidentalis"] },
  { names: ["Hibiscus moscheutos"], files: ["hibiscus-moscheutos"] },
  { names: ["Hydrophyllum appendiculatum"], files: ["hydrophyllum-appendiculatum"] },
  { names: ["Impatiens pallida"], files: ["impatiens-pallida"] },
  { names: ["Iris cristata"], files: ["iris-cristata"] },
  { names: ["Iris virginica"], files: ["iris-virginica"] },
  { names: ["Krigia biflora"], files: ["krigia-biflora"] },
  { names: ["Lepidium virginicum"], files: ["lepidium-virginicum"] },
  { names: ["Liatris aspera"], files: ["liatris-aspera"] },
  { names: ["Liatris spicata"], files: ["liatris-spicata"] },
  { names: ["Lilium michiganense"], files: ["lilium-michiganense"] },
  { names: ["Lilium philadelphicum"], files: ["lilium-philadelphicum"] },
  { names: ["Lobelia cardinalis"], files: ["lobelia-cardinalis"] },
  { names: ["Maianthemum racemosum"], files: ["maianthemum-racemosum"] },
  { names: ["Manfreda virginica"], files: ["manfreda-virginica"] },
  { names: ["Mertensia virginica"], files: ["mertensia-virginica"] },
  { names: ["Monarda didyma"], files: ["monarda-didyma"] },
  { names: ["Monarda fistulosa"], files: ["monarda-fistulosa"] },
  { names: ["Monarda punctata"], files: ["monarda-punctata"] },
  { names: ["Nabalus racemosus","Prenanthes racemosa"], files: ["nabalus-racemosus"] },
  { names: ["Oenothera biennis"], files: ["oenothera-biennis"] },
  { names: ["Oenothera fruticosa"], files: ["oenothera-fruticosa"] },
  { names: ["Onoclea sensibilis"], files: ["onoclea-sensibilis"] },
  { names: ["Opuntia humifusa"], files: ["opuntia-humifusa"] },
  { names: ["Oxalis stricta"], files: ["oxalis-stricta"] },
  { names: ["Oxalis violacea"], files: ["oxalis-violacea"] },
  { names: ["Packera obovata"], files: ["packera-obovata"] },
  { names: ["Panicum virgatum"], files: ["panicum-virgatum"] },
  { names: ["Passiflora incarnata"], files: ["passiflora-incarnata"] },
  { names: ["Penstemon calycosus"], files: ["penstemon-calycosus"] },
  { names: ["Penstemon digitalis"], files: ["penstemon-digitalis"] },
  { names: ["Persicaria pensylvanica"], files: ["persicaria-pensylvanica"] },
  { names: ["Phlox divaricata"], files: ["phlox-divaricata"] },
  { names: ["Physostegia virginiana"], files: ["physostegia-virginiana"] },
  { names: ["Plantago rugelii"], files: ["plantago-rugelii"] },
  { names: ["Polanisia dodecandra"], files: ["polanisia-dodecandra"] },
  { names: ["Polemonium reptans"], files: ["polemonium-reptans"] },
  { names: ["Prunella vulgaris"], files: ["prunella-vulgaris"] },
  { names: ["Prunus angustifolia"], files: ["prunus-angustifolia"] },
  { names: ["Prunus serotina"], files: ["prunus-serotina"] },
  { names: ["Pseudognaphalium obtusifolium"], files: ["pseudognaphalium-obtusifolium"] },
  { names: ["Pycnanthemum virginianum"], files: ["pycnanthemum-virginianum"] },
  { names: ["Quercus alba"], files: ["quercus-alba"] },
  { names: ["Ratibida pinnata"], files: ["ratibida-pinnata"] },
  { names: ["Rosa setigera"], files: ["rosa-setigera"] },
  { names: ["Rudbeckia hirta","Rudebeckia hirta"], files: ["rudbeckia-hirta"] },
  { names: ["Ruellia humilis"], files: ["ruellia-humilis"] },
  { names: ["Sabatia angularis"], files: ["sabatia-angularis"] },
  { names: ["Sagittaria latifolia"], files: ["sagittaria-latifolia"] },
  { names: ["Sambucus canadensis"], files: ["sambucus-canadensis"] },
  { names: ["Scrophularia marilandica"], files: ["scrophularia-marilandica"] },
  { names: ["Scutellaria incana"], files: ["scutellaria-incana"] },
  { names: ["Sedum pulchellum"], files: ["sedum-pulchellum"] },
  { names: ["Sedum ternatum"], files: ["sedum-ternatum"] },
  { names: ["Silene regia"], files: ["silene-regia"] },
  { names: ["Silene virginica"], files: ["silene-virginica"] },
  { names: ["Silphium trifoliatum"], files: ["silphium-trifoliatum"] },
  { names: ["Sisyrinchium angustifolium"], files: ["sisyrinchium-angustifolium"] },
  { names: ["Solidago caesia"], files: ["solidago-caesia-1","solidago-caesia-2"] },
  { names: ["Solidago rigida"], files: ["solidago-rigida"] },
  { names: ["Symphyotrichum cordifolium"], files: ["symphyotrichum-cordifolium"] },
  { names: ["Symphyotrichum laeve"], files: ["symphyotrichum-laeve"] },
  { names: ["Symphyotrichum novae-angliae"], files: ["symphyotrichum-novae-angliae"] },
  { names: ["Symphyotrichum pilosum"], files: ["symphyotrichum-pilosum"] },
  { names: ["Symphyotrichum shortii"], files: ["symphyotrichum-shortii"] },
  { names: ["Thalictrum thalictroides"], files: ["thalictrum-thalictroides"] },
  { names: ["Tradescantia ohiensis","Tradescantia ohioensis"], files: ["tradescantia-ohiensis"] },
  { names: ["Tradescantia virginiana"], files: ["tradescantia-virginiana"] },
  { names: ["Trillium erectum"], files: ["trillium-erectum"] },
  { names: ["Trillium sessile"], files: ["trillium-sessile"] },
  { names: ["Verbena urticifolia"], files: ["verbena-urticifolia"] },
  { names: ["Verbesina virginica"], files: ["verbesina-virginica"] },
  { names: ["Vernonia missurica"], files: ["vernonia-missurica"] },
  { names: ["Viburnum acerifolium"], files: ["viburnum-acerifolium"] },
  { names: ["Viola sororia"], files: ["viola-sororia"] },
  { names: ["Viola sororia var. rubra","Viola sororia f. rubra"], files: ["viola-sororia-var-rubra"] },
  { names: ["Wisteria frutescens"], files: ["wisteria-frutescens"] },
  { names: ["Zizia aurea"], files: ["zizia-aurea"] }
];

// Species we have photos of that are not in the Sheet yet. Each shows as a photo-only card until a plant with the
// same botanical name appears in plant-data.js; from then on the Sheet's entry is used (and gets the photo above).
window.PLANT_PHOTO_ONLY = [
  { name: "Pearly Everlasting", botanical: "Anaphalis margaritacea", category: "Forbs & Ferns", altNames: "Pearly Everlasting, Western Pearly Everlasting, Pearl Everlasting" },
  { name: "Wild Basil", botanical: "Clinopodium vulgare", category: "Forbs & Ferns", altNames: "Wild Basil, Cushion Calamint, Dogmint, Field Basil" },
  { name: "Lowland Brittle Fern", botanical: "Cystopteris protrusa", category: "Forbs & Ferns", altNames: "Lowland Brittle Fern, Lowland Fragile Fern, Lowland Bladder Fern" },
  { name: "Poverty Oatgrass", botanical: "Danthonia spicata", category: "Grasses & Sedges", altNames: "Poverty Oatgrass, Poverty Danthonia, Poverty Grass" },
  { name: "White Trout Lily", botanical: "Erythronium albidum", category: "Forbs & Ferns", altNames: "White Trout Lily, White Fawn Lily, White Dog's-tooth Violet" },
  { name: "Virginia Pepperweed", botanical: "Lepidium virginicum", category: "Forbs & Ferns", altNames: "Virginia Pepperweed, Poorman's Pepperweed, Peppergrass, Least Pepperwort" },
  { name: "False Solomon's Seal", botanical: "Maianthemum racemosum", category: "Forbs & Ferns", altNames: "False Solomon's Seal, Feathery False Lily of the Valley, Solomon's Plume, False Spikenard, Treacleberry" },
  { name: "Sensitive Fern", botanical: "Onoclea sensibilis", category: "Forbs & Ferns", altNames: "Sensitive Fern, Bead Fern" },
  { name: "Blackseed Plantain", botanical: "Plantago rugelii", category: "Forbs & Ferns", altNames: "Blackseed Plantain, Rugel's Plantain, American Plantain, Pale Plantain" },
  { name: "American Wisteria", botanical: "Wisteria frutescens", category: "Vines", altNames: "American Wisteria" }
];
